### ISSUE TITLE
ModuleNotFoundError: No module named 'bot.utils.tg_manager.TGSession'

### ISSUE THREAD

**Issue by MadSaint777** [Desamod/GoblinMineBot#1]
Traceback (most recent call last):
  File "C:\Users\Admin\GoblinMineBot\main.py", line 5, in <module>
    from bot.utils import logger
  File "C:\Users\Admin\GoblinMineBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\Admin\GoblinMineBot\bot\utils\launcher.py", line 9, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\Admin\GoblinMineBot\bot\core\tapper.py", line 16, in <module>
    from ..utils.tg_manager.TGSession import TGSession
ModuleNotFoundError: No module named 'bot.utils.tg_manager.TGSession'

**Comment by Desamod** [comment]
Platform? Python version?

**Comment by MadSaint777** [comment]
Windows 10. Python 3.11.5

**Comment by Desamod** [comment]
Please, read README first, you need to use python 3.10

**Comment by MadSaint777** [comment]
im install 3.10 this command.
py -3.10-64 -m venv venv

**Comment by MadSaint777** [comment]
Skipping .env copying
Starting the bot...
Traceback (most recent call last):
  File "C:\Users\Admin\GoblinMineBot\main.py", line 5, in <module>
    from bot.utils import logger
  File "C:\Users\Admin\GoblinMineBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\Admin\GoblinMineBot\bot\utils\launcher.py", line 12, in <module>
    from bot.core.TgManager.tg_manager import SessionManager
ImportError: DLL load failed while importing tg_manager: %1 не является приложением Win32.
done
PLEASE EDIT .ENV FILE
Для продолжения нажмите любую клавишу . . .

(venv) Admin@DESKTOP-BVRF2JK C:\Users\Admin\GoblinMineBot
$ python -V
Python 3.10.6
